### ISSUE TITLE
If bin dir does not exists composer install/update failed 

### ISSUE THREAD

**Issue by mfuehrer82** [tommy-muehle/tooly-composer-script#10]
### Expected behavior
- Create bin dir if it does not exist and install tools
### Actual behavior
- Installation failed with 
``
[ErrorException]
  scandir(/app/path/bin): failed to open dir: No such file or directory 
``

### Steps to reproduce actual behavior
- Delete bin dir and run composer update
- Error occured into $this->removeFromDir() 

### Other information (e.g. version, os system, stacktraces, etc) 
- tooly version 1.2.3

**Comment by tommy-muehle** [comment]
Good catch @mfuehrer82. Thank you. I had [a condition](https://github.com/tommy-muehle/tooly-composer-script/blob/master/src/Script/Processor.php#L54) to do this. But the "createDirectory" Method was originally created for files. So dirname() was called inside. And the result was that only the parent directory was checked if it existing.

I fixed it and release a new version 1.2.4 to solve this issue.

**Comment by mfuehrer82** [comment]
Hey, 
thanks for the fast reply. But i think that did not solve the problem i had. I had an error in the removeFromDir method. I add a fix into my fork and also add a test for it. Please give me some feedback what you think about.

**Comment by tommy-muehle** [comment]
Hi,
have you updated your fork? Add the "removeFromDir" method calls are part of the "cleanUp" method in which the condition still exist a few lines before.

```
if (false === is_dir($composerBinDirectory)) {
    $this->helper->getFilesystem()->createDirectory($composerBinDirectory);
}

$this->removeFromDir($composerBinDirectory);
$this->removeFromDir(...);
```
